Repository SwaprHQ/stackly-ui, pull requests merged in 2023-06, with the labels that each got.

#15 Add Modal and Dialog component
  package.json
  packages/app/app/page.tsx
  packages/app/app/ui/page.tsx
  packages/app/components/navbar/Navbar.tsx
  packages/app/components/stackbox/ConfirmStackModal.tsx
  packages/app/components/stackbox/StackTransactionLoading.tsx
  packages/app/components/stackbox/Stackbox.tsx
  packages/app/components/token-picker/TokenPicker.tsx
  packages/app/package.json
  packages/app/public/assets/images/dots-spinner.svg
  packages/app/tailwind.config.js
  packages/app/ui/buttons/Button.tsx
  packages/app/ui/buttons/RadioButton.tsx
  packages/app/ui/buttons/base.ts
  packages/app/ui/dialog/Dialog.tsx
  packages/app/ui/dialog/DialogContent.tsx
  packages/app/ui/dialog/DialogFooterActions.tsx
  packages/app/ui/dialog/index.ts
  packages/app/ui/index.ts
  packages/app/ui/modal/Modal.tsx
  packages/app/ui/modal/ModalContent.tsx
  packages/app/ui/modal/ModalFooter.tsx
  packages/app/ui/modal/ModalHeader.tsx
  packages/app/ui/modal/ModalHeaderTitle.tsx
  packages/app/ui/modal/index.ts
  yarn.lock
Labels: design system

#17 feat: Add stacks page with empty state
  packages/app/app/stacks/empty-state.tsx
  packages/app/app/stacks/page.tsx
  packages/app/app/ui/page.tsx
  packages/app/components/navbar/MobileMenuList.tsx
  packages/app/components/navbar/Navbar.tsx
  packages/app/public/assets/images/dots-spinner.svg
  packages/app/public/assets/images/empty-state-stacks-coins.svg
  packages/app/public/assets/images/stackly-logo-icon.svg
  packages/app/public/assets/images/stackly-logo-name.svg
  packages/app/ui/buttons/base.ts
Labels: feature

#18 feat: add Your stacks header and tabs
  packages/app/app/layout.tsx
  packages/app/app/stacks/empty-state.tsx
  packages/app/app/stacks/layout.tsx
  packages/app/app/stacks/page.tsx
  packages/app/app/stacks/table.tsx
  packages/app/components/stackbox/Stackbox.tsx
  packages/app/package.json
  packages/app/tailwind.config.js
  yarn.lock
Labels: feature

#20 chore: install connect-kit and viem
  packages/app/package.json
  yarn.lock
Labels: chore

#21 feat: add connect button
  .gitignore
  packages/app/.env.example
  packages/app/app/layout.tsx
  packages/app/app/page.tsx
  packages/app/components/ConnectButton.tsx
  packages/app/components/index.ts
  packages/app/components/navbar/MobileMenu.tsx
  packages/app/components/navbar/Navbar.tsx
  packages/app/components/navbar/index.ts
  packages/app/components/stackbox/Stackbox.tsx
  packages/app/next.config.js
  packages/app/providers/Providers.tsx
  packages/app/providers/index.ts
  packages/app/providers/wagmi-config.ts
  packages/app/ui/buttons/Button.tsx
Labels: feature

#23 feat: add stack order modal
  packages/app/app/stacks/components/OrdersProgressText.tsx
  packages/app/app/stacks/components/StacksTable.tsx
  packages/app/app/stacks/page.tsx
  packages/app/app/ui/page.tsx
  packages/app/components/FromToStackTokenPair.tsx
  packages/app/components/OrdersProgressBar.tsx
  packages/app/components/StackedTokenLogoPair.tsx
  packages/app/components/StacksTable.tsx
  packages/app/components/navbar/Navbar.tsx
  packages/app/components/stack-modal/StackModal.tsx
  packages/app/components/stack-modal/StackProgress.tsx
  packages/app/components/stack-modal/StackTransactionsTable.tsx
  packages/app/components/stackbox/ConfirmStackModal.tsx
  packages/app/components/stackbox/StackTransactionLoading.tsx
  packages/app/components/token-picker/TokenPicker.tsx
  packages/app/models/order/index.ts
  packages/app/models/order/order.ts
  packages/app/models/order/types.ts
  packages/app/ui/dialog/Dialog.tsx
  packages/app/ui/modal/Modal.tsx
  packages/app/ui/modal/ModalContent.tsx
  packages/app/ui/modal/ModalHeader.tsx
  packages/app/ui/modal/ModalHeaderTitle.tsx
  packages/app/ui/table/Table.tsx
  packages/app/ui/text/BodyText.tsx
  packages/app/utils/datetime.ts
  packages/app/utils/numbers.ts
Labels: feature

#22 feat: add select network
  .gitignore
  packages/app/app/layout.tsx
  packages/app/app/page.tsx
  packages/app/components/ConnectButton.tsx
  packages/app/components/SelectNetwork.tsx
  packages/app/components/index.ts
  packages/app/components/navbar/MobileMenu.tsx
  packages/app/components/navbar/Navbar.tsx
  packages/app/ui/buttons/Button.tsx
Labels: feature

#25 chore: move subgraph package to this repo
  .gitignore
  packages/subgraph/.eslintrc
  packages/subgraph/abis/DCAOrder.json
  packages/subgraph/abis/ERC20.json
  packages/subgraph/abis/OrderFactory.json
  packages/subgraph/bin/build-subgraph.ts
  packages/subgraph/bin/config.ts
  packages/subgraph/package.json
  packages/subgraph/schema.graphql
  packages/subgraph/src/mappings/factory.ts
  packages/subgraph/src/mappings/order.ts
  yarn.lock
Labels: chore
