Repository SwaprHQ/stackly-ui, pull requests merged in 2023-08, with the labels that each got.

#31 feat[STK-33]: create stack frequency section
  packages/app/app/layout.tsx
  packages/app/app/ui/page.tsx
  packages/app/components/DatePicker.tsx
  packages/app/components/index.ts
  packages/app/components/stackbox/Stackbox.tsx
  packages/app/components/token-picker/index.ts
  packages/app/package.json
  packages/app/styles/global.css
  packages/app/ui/Calendar.tsx
  packages/app/ui/buttons/index.ts
  packages/app/ui/index.ts
  yarn.lock
Labels: feature

#33 feat: get chain and address from wallet and improve stacks calculations
  packages/app/.env.example
  packages/app/app/not-found.tsx
  packages/app/app/stacks/page.tsx
  packages/app/app/stacks/stacks-orders.tsx
  packages/app/components/ConnectButton.tsx
  packages/app/components/SelectNetwork.tsx
  packages/app/components/StackedTokenLogoPair.tsx
  packages/app/components/StacksTable.tsx
  packages/app/components/stack-modal/StackModal.tsx
  packages/app/components/stack-modal/StackOrdersTable.tsx
  packages/app/components/stack-modal/StackProgress.tsx
  packages/app/models/cow-order/cow-order.ts
  packages/app/models/order/order.ts
  packages/app/models/stack-order/fetcher.ts
  packages/app/models/stack-order/stack-order.ts
  packages/app/package.json
  packages/app/public/assets/images/stacks.svg
  yarn.lock
Labels: feature

#35 [STK-75][FEAT] - Add Toast component
  packages/app/app/ui/page.tsx
  packages/app/components/stackbox/Stackbox.tsx
  packages/app/contexts/ModalContext.tsx
  packages/app/ui/icon/Icon.tsx
  packages/app/ui/index.ts
  packages/app/ui/modal/Modal.tsx
  packages/app/ui/toast/Toast.tsx
Labels: feature

#42 feat[STK-34]: create stack confirmation modal
  packages/app/app/ui/page.tsx
  packages/app/components/stackbox/ConfirmStackModal.tsx
  packages/app/components/stackbox/Stackbox.tsx
  packages/app/contexts/ModalContext.tsx
  packages/app/models/stack/index.ts
  packages/app/models/stack/types.ts
  packages/app/tailwind.config.js
Labels: feature

#50 update: refactor mobile menu to have all the code in one place
  packages/app/components/navbar/MenuButton.tsx
  packages/app/components/navbar/MobileMenu.tsx
  packages/app/components/navbar/MobileMenuList.tsx
Labels: refactor

#49 fix: changing network on mobile when menu is open
  packages/app/components/SelectNetwork.tsx
Labels: bug

#47 feat: show when a stack is finished but has funds
  packages/app/components/StacksTable.tsx
  packages/app/components/stack-modal/StackModal.tsx
  packages/app/models/order/order.ts
  packages/app/models/stack-order/stack-order.ts
Labels: feature

#59 fix: add correct padding to datepicker button
  packages/app/components/stackbox/Stackbox.tsx
Labels: design-review

#58 fix: divider should be full length on stackbox
  packages/app/app/layout.tsx
  packages/app/components/stackbox/Stackbox.tsx
Labels: design-review

#60 fix: outline stroke on radio buttons should be lighter
  packages/app/ui/buttons/RadioButton.tsx
  packages/app/ui/buttons/base.ts
Labels: design-review

#61 fix: network switcher over overlay
  packages/app/components/DatePicker.tsx
  packages/app/components/SelectNetwork.tsx
Labels: bug

#64 update: Button styles
  packages/app/app/stacks/empty-state.tsx
  packages/app/app/stacks/no-wallet-state.tsx
  packages/app/app/stacks/stacksOrders.tsx
  packages/app/app/ui/page.tsx
  packages/app/components/ConnectButton.tsx
  packages/app/components/SelectNetwork.tsx
  packages/app/components/StacksTable.tsx
  packages/app/components/stackbox/ConfirmStackModal.tsx
  packages/app/components/stackbox/Stackbox.tsx
  packages/app/ui/buttons/base.ts
  packages/app/ui/dialog/DialogFooterActions.tsx
Labels: design-review
