Repository SwaprHQ/stackly-ui, pull requests merged in 2023-07, with the labels that each got.

#26 feat: get data from Cow API and create new models to handle logic
  packages/app/app/stacks/components/CellWrapper.tsx
  packages/app/app/stacks/components/OrdersProgressText.tsx
  packages/app/app/stacks/components/StacksTable.tsx
  packages/app/app/stacks/no-wallet-state.tsx
  packages/app/app/stacks/page.tsx
  packages/app/components/ConnectButton.tsx
  packages/app/components/FromToStackTokenPair.tsx
  packages/app/components/StacksTable.tsx
  packages/app/components/stack-modal/StackModal.tsx
  packages/app/components/stack-modal/StackOrdersTable.tsx
  packages/app/components/stack-modal/StackProgress.tsx
  packages/app/components/stack-modal/StackTransactionsTable.tsx
  packages/app/models/cow-order/cow-order.ts
  packages/app/models/cow-order/fetcher.ts
  packages/app/models/cow-order/index.ts
  packages/app/models/order/fetcher.ts
  packages/app/models/order/index.ts
  packages/app/models/stack-order/fetcher.ts
  packages/app/models/stack-order/filters.ts
  packages/app/models/stack-order/index.ts
  packages/app/models/stack-order/stack-order.ts
  packages/app/models/stack-order/types.ts
  packages/app/models/token/index.ts
  packages/app/package.json
  packages/app/public/assets/images/no-wallet-state.svg
  packages/app/utils/datetime.ts
  packages/app/utils/token.ts
  yarn.lock
Labels: feature

#28 feat: bring SDK package
  .github/workflows/CI.yml
  package.json
  packages/sdk/.eslintrc
  packages/sdk/.prettierignore
  packages/sdk/abis/DCAOrder.json
  packages/sdk/abis/ERC20.json
  packages/sdk/abis/ERC20Bytes32.json
  packages/sdk/abis/Multicall.json
  packages/sdk/abis/OrderFactory.json
  packages/sdk/babel.config.js
  packages/sdk/bin/typechain.js
  packages/sdk/package.json
  packages/sdk/src/abis/multicall.ts
  packages/sdk/src/constants.ts
  packages/sdk/src/entities/Amount.ts
  packages/sdk/src/entities/BaseCurrency.ts
  packages/sdk/src/entities/Currency.ts
  packages/sdk/src/entities/Ether.ts
  packages/sdk/src/entities/NativeCurrency.ts
  packages/sdk/src/entities/WrappedTokenInfo.ts
  packages/sdk/src/entities/defaultTokens.ts
  packages/sdk/src/entities/index.ts
  packages/sdk/src/entities/token.ts
  packages/sdk/src/entities/xDAI.ts
  packages/sdk/src/index.ts
  packages/sdk/src/utils/isAddress.ts
  packages/sdk/src/utils/validateAndParseAddress.ts
  packages/sdk/src/vaults/constants.ts
  packages/sdk/src/vaults/factory.ts
  packages/sdk/src/vaults/index.ts
  packages/sdk/src/vaults/subgraph.ts
  packages/sdk/tsconfig.json
  yarn.lock
Labels: chore

#32 [STK-89][FEAT] - TokenPicker token select functionality
  README.md
  package.json
  packages/app/app/page.tsx
  packages/app/app/stacks/no-wallet-state.tsx
  packages/app/components/TokenIcon.tsx
  packages/app/components/index.ts
  packages/app/components/navbar/Logo.tsx
  packages/app/components/stackbox/ConfirmStackModal.tsx
  packages/app/components/stackbox/StackTransactionLoading.tsx
  packages/app/components/stackbox/Stackbox.tsx
  packages/app/components/stackbox/index.ts
  packages/app/components/token-picker/TokenPicker.tsx
  packages/app/components/token-picker/constants.ts
  packages/app/public/assets/icons/caret.svg
  packages/app/public/assets/icons/index.tsx
  packages/app/public/assets/icons/stackly-logo.svg
  packages/app/public/assets/images/empty-state-no-wallet.svg
  packages/app/public/assets/images/index.tsx
  packages/app/public/assets/images/tokens/index.tsx
  packages/app/public/assets/index.ts
  packages/app/ui/buttons/ChipButton.tsx
  packages/app/ui/icon/Icon.tsx
  yarn.lock
Labels: feature

#11 feat: add meta open graph and twitter images
  packages/app/.env.example
  packages/app/app/layout.tsx
  packages/app/app/opengraph-image.jpg
  packages/app/app/twitter-image.jpg
  packages/app/package.json
  yarn.lock
Labels: feature, chore, pending
