Repository SwaprHQ/stackly-ui, pull requests merged in 2023-11, with the labels that each got.

#133 feat: swap from <-> to tokens when clicking stackbox arrow icon
  packages/app/components/stackbox/Stackbox.tsx
Labels: feature

#132 Update: Add ellipsis to token amount input
  packages/app/components/stackbox/Stackbox.tsx
Labels: enhancement

#131 Update: Stackbox limit decimals to 6 when selecting balance options o…
  packages/app/components/stackbox/Stackbox.tsx
Labels: enhancement

#137 [SWA-212][REFACTOR] - Change FA implementation approach and add extra events
  bun.lockb
  package.json
  packages/app/analytics/constants.ts
  packages/app/analytics/index.ts
  packages/app/analytics/types.ts
  packages/app/app/layout.tsx
  packages/app/components/FathomAnalytics.tsx
  packages/app/components/index.ts
  packages/app/components/stackbox/ConfirmStackModal.tsx
  packages/app/components/stackbox/Stackbox.tsx
  packages/app/components/strategies/StrategyCard.tsx
  packages/app/contexts/AnalyticsContext.tsx
  packages/app/contexts/index.ts
  packages/app/models/index.ts
  packages/app/providers/Providers.tsx
  packages/app/utils/index.ts
  packages/app/utils/time.ts
  packages/landing/analytics/index.ts
  packages/landing/analytics/types.ts
  packages/landing/app/layout.tsx
  packages/landing/components/FathomAnalytics.tsx
  packages/landing/components/index.ts
  packages/landing/components/navbar/MobileMenu.tsx
  packages/landing/components/navbar/Navbar.tsx
  packages/landing/components/sections/FAQ/FAQ.tsx
  packages/landing/components/sections/HeroBanner/HeroBanner.tsx
  packages/landing/components/sections/TryStacklyBanner/TryStacklyBanner.tsx
  packages/landing/contexts/AnalyticsContext.tsx
  packages/landing/contexts/index.ts
  packages/landing/providers/Providers.tsx
  packages/landing/providers/index.ts
Labels: chore
